CREATE TABLE PLAYER(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT PLAYER_PK PRIMARY KEY,
    NAME VARCHAR(40)
);
CREATE TABLE SCOREBOARD(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT SCOREBOARD_PK PRIMARY KEY,
    INSERT_DATE DATE NOT NULL,
    PLAYER_ID INT NOT NULL REFERENCES PLAYER
);
CREATE TABLE SCORE(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT SCORE_PK PRIMARY KEY,
    DTYPE VARCHAR(40) NOT NULL,
    INDEX INT,
    NAME VARCHAR(40) NOT NULL,
    VALUE INT
);
CREATE TABLE SCOREBOARD_CLOSEDSCORE(
    SCOREBOARD_ID INT NOT NULL REFERENCES SCOREBOARD,
    SCORE_ID INT NOT NULL REFERENCES SCORE
);
CREATE TABLE SCOREBOARD_OPENSCORE(
    SCOREBOARD_ID INT NOT NULL REFERENCES SCOREBOARD,
    SCORE_ID INT NOT NULL REFERENCES SCORE
);
CREATE TABLE DIE(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT DIE_PK PRIMARY KEY,
    VALUE INT NOT NULL,
    IS_LOCKED BOOLEAN
);
CREATE TABLE TURN(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT TURN_PK PRIMARY KEY,
    SCOREBOARD_ID INT NOT NULL REFERENCES SCOREBOARD,
    NUMBER_OF_ROLLS INT NOT NULL
);
CREATE TABLE TURN_DIE(
    TURN_ID INT NOT NULL REFERENCES TURN,
    DIE_ID INT NOT NULL REFERENCES DIE
);