CREATE TABLE PLAYER(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT PLAYER_PK PRIMARY KEY,
    NAME VARCHAR(40)
);
CREATE TABLE SCOREBOARD(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT SCOREBOARD_PK PRIMARY KEY,
    INSERT_DATE DATE NOT NULL,
    PLAYER_ID INT NOT NULL REFERENCES PLAYER
);
CREATE TABLE SCORE(
  ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT SCORE_PK PRIMARY KEY,
  DTYPE VARCHAR(40) NOT NULL,
  INDEX INT,
  NAME VARCHAR(40) NOT NULL,
  VALUE INT
);
CREATE TABLE SCOREBOARD_SCORE(
    SCOREBOARD_ID INT NOT NULL REFERENCES SCOREBOARD,
    SCORE_ID INT NOT NULL REFERENCES SCORE
);